### ISSUE TITLE
Updating the google drive link of the Species OOD dataset

### ISSUE THREAD

**Issue by PKUCSS** [hendrycks/anomaly-seg#28]
Thanks for your excellent work! I'm working on OOD detection and plan to conduct experiments on your ImageNet vs. Species benchmark, but when I use Linux commands to download the Species folder to my server, there is an error "two many users have viewed or downloaded this file recently."  I'm still able to access the link in the browser, but the files are too large for directly downloading on my PC. Could you please consider updating the sharing link to facilitate the evaluation on your novel benchmark? Thanks very much.

**Comment by PKUCSS** [comment]
@hendrycks Could you please consider updating the link to the Species dataset due to the issue stated in the last comment?  Thank you very much

**Comment by hendrycks** [comment]
It seems to work for me now, having just tried it. Is this still an issue for you?

**Comment by YoojLee** [comment]
Similar issue here! :( I have been trying to download the species dataset via the google drive link but failed with a network error (It stopped being downloaded after 25% of the progress..)

**Comment by xksteven** [comment]
Finding good hosting is difficult and can be expensive over time.  Google sometimes blocks the automatic loaders or other APIs which is unfortunate.  We're sorry for the inconvenience this provides.  If anyone has a good hosting platform they're running I'd be happy to upload it there.

Otherwise I'm going to close this issue as I have confirmed that I am able to download the entire dataset via Google drive.
