### ISSUE TITLE
Question about Training Procedure

### ISSUE THREAD

**Issue by hyunjunju** [hendrycks/anomaly-seg#5]
Thank you for your hard work.

I have some questions.
1) In the training procedure, does the data and segmentation map are downsampled?
According to the code, I think the model uses the downsampled images and segmentation maps.
Is it for efficient training?

2) In the validation procedure, is interpolation operation added after the trained model to just matching the segmentation size?

Thanks

**Comment by xksteven** [comment]
> 1. In the training procedure, does the data and segmentation map are downsampled?
>    According to the code, I think the model uses the downsampled images and segmentation maps.
>    Is it for efficient training?

The images and labels are downsampled.  The purpose for this is twofold.  
One is for ease of implementation because handling images of various sizes makes designing and structuring the network more difficult.
The second is for efficiency we have experimentally observed that increasing the batch size leads to increased performance and having images of various sizes and large makes having a large batch size difficult.

> 2. In the validation procedure, is interpolation operation added after the trained model to just matching the segmentation size?

The original labels have their own respective dimensions.  It is almost as if one is being dishonest if one only evaluates on the downsampled versions.  Hence the interpolation or upsampling is performed at test time or for evaluation.

Hope that clarifies your questions!
